"""create planets table

Revision ID: 4d96c1133fa6
Revises: 362abc647316
Create Date: 2025-05-06 12:53:56.708401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d96c1133fa6'
down_revision = '362abc647316'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("planets") as batch_op:
        batch_op.alter_column(
            "distance_from_sun",
            type_=sa.Float(),
            postgresql_using="distance_from_sun::double precision",
            existing_nullable=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.alter_column('distance_from_sun',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
