"""create moons table and fk to planets

Revision ID: c4da19986438
Revises: 4d96c1133fa6
Create Date: 2025-05-06 15:27:51.593542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4da19986438'
down_revision = '4d96c1133fa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('orbital_period', sa.Float(), nullable=True),
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moons')
    # ### end Alembic commands ###
